[upstream]
peer_address = "preprod-node.world.dev.cardano.org:30000"
network_magic = 1
is_testnet = true

[storage]
version = "v1"
path = "/data"
max_wal_history = 10000
max_chain_history = 10000

[genesis]
byron_path = "/etc/dolos/byron.json"
shelley_path = "/etc/dolos/shelley.json"
alonzo_path = "/etc/dolos/alonzo.json"
conway_path = "/etc/dolos/conway.json"

[chain]
type = "cardano"
account_state = true

[chain.track]
account_state = true
asset_state = true
pool_state = true
epoch_state = true
drep_state = true
proposal_logs = true
tx_logs = true
account_logs = true
pool_logs = true
epoch_logs = true

[sync]
pull_batch_size = 100

[submit]
prune_height = 200

[serve.grpc]
listen_address = "[::]:50051"

[serve.minibf]
listen_address = "[::]:3000"

[serve.ouroboros]
listen_path = "/data/dolos.socket"
magic = 1

[relay]
listen_address = "[::]:30031"
magic = 1

[mithril]
aggregator = "https://aggregator.release-preprod.api.mithril.network/aggregator"

[logging]
max_level = "INFO"
include_tokio = false
include_pallas = false
include_grpc = false
