[source.mithril]
aggregator = "https://aggregator.release-preprod.api.mithril.network/aggregator"

[upstream]
peer_address = "preprod-node.world.dev.cardano.org:30000"
network_magic = 1
is_testnet = true

[storage]
path = "/data"

[network]
magic = 1

[serve.grpc]
listen_address = "[::]:50051"

[serve.minibf]
listen_address = "[::]:3000"

[serve.ouroboros]
listen_path = "/data/dolos.socket"
magic = 1

[relay]
listen_address = "[::]:30031"
magic = 1

[logging]
max_level = "info"

