[source.mithril]
aggregator = "https://aggregator.release-mainnet.api.mithril.network/aggregator"

[storage]
path = "/data"

[network]
magic = 764824073

[serve.grpc]
listen_address = "[::]:50051"

[serve.minibf]
listen_address = "[::]:3000"

[serve.ouroboros]
listen_path = "/data/dolos.socket"
magic = 764824073

[relay]
listen_address = "[::]:30031"
magic = 764824073

[logging]
max_level = "info"

