[upstream]
peer_address = "relays-new.cardano-mainnet.iohk.io:3001"
network_magic = 764824073
is_testnet = false

[storage]
version = "v1"
path = "/data"
max_wal_history = 10000
max_chain_history = 10000

[genesis]
byron_path = "/etc/dolos/byron.json"
shelley_path = "/etc/dolos/shelley.json"
alonzo_path = "/etc/dolos/alonzo.json"
conway_path = "/etc/dolos/conway.json"

[chain]
type = "cardano"
account_state = true

[chain.track]
account_state = true
asset_state = true
pool_state = true
epoch_state = true
drep_state = true
proposal_logs = true
tx_logs = true
account_logs = true
pool_logs = true
epoch_logs = true

[sync]
pull_batch_size = 100

[submit]
prune_height = 200

[serve.grpc]
listen_address = "[::]:50051"

[serve.minibf]
listen_address = "[::]:3000"

[serve.ouroboros]
listen_path = "/data/dolos.socket"
magic = 764824073

[relay]
listen_address = "[::]:30031"
magic = 764824073

[mithril]
aggregator = "https://aggregator.release-mainnet.api.mithril.network/aggregator"
genesis_key = "5b3139312c36362c3134302c3138352c3133382c31312c3233372c3230372c3235302c3134342c32372c322c3138382c33302c31322c38312c3135352c3230342c31302c3137392c37352c32332c3133382c3139362c3231372c352c31342c32302c35372c37392c33392c3137365d"

[logging]
max_level = "INFO"
include_tokio = false
include_pallas = false
include_grpc = false
