[upstream]
peer_address = "relays-new.cardano-mainnet.iohk.io:3001"
network_magic = 764824073
is_testnet = false

[storage]
version = "v1"
path = "/data"
max_wal_history = 10000
max_chain_history = 10000

[genesis]
byron_path = "/etc/dolos/byron.json"
shelley_path = "/etc/dolos/shelley.json"
alonzo_path = "/etc/dolos/alonzo.json"
conway_path = "/etc/dolos/conway.json"

[chain]
type = "cardano"

[chain.track]
seen_addresses = true
asset_state = true
pool_state = true
pool_delegator = true
epoch_state = true
account_activity = true

[sync]
pull_batch_size = 100

[submit]
prune_height = 200

[serve.grpc]
listen_address = "[::]:50051"

[serve.minibf]
listen_address = "[::]:3000"

[serve.ouroboros]
listen_path = "/data/dolos.socket"
magic = 764824073

[relay]
listen_address = "[::]:30031"
magic = 764824073

[mithril]
aggregator = "https://aggregator.release-mainnet.api.mithril.network/aggregator"

[logging]
max_level = "INFO"
include_tokio = false
include_pallas = false
include_grpc = false
